#%RAML 1.0 Library
usage: Collection to Centralize Data Types for MC University Records APIs

types:
  studentDataType: !include dataTypes/students.raml
  studentsListDataType: !include dataTypes/students.raml
  bookDataType: !include dataTypes/books.raml
  booksListDataType: !include dataTypes/books.raml
  sportDataType: !include dataTypes/sports.raml
  sportsListDataType: !include dataTypes/sports.raml