#%RAML 1.0 Library
usage: Collection to Centralize Data Types for MC University Records APIs

types:
  studentGetResponseDataType: !include dataTypes/studentsGetResponseDataType.raml
  studentListGetResponseDataType: !include dataTypes/studentsGetResponseDataType.raml
  studentCreateResponseDataType: !include dataTypes/studentsGetResponseDataType.raml
  studentUpdateResponseDataType: !include dataTypes/studentsGetResponseDataType.raml
  studentDeleteResponseDataType: !include dataTypes/studentsGetResponseDataType.raml
  bookGetResponseDataType: !include dataTypes/booksGetResponseDataType.raml
  booksListGetResponseDataType: !include dataTypes/booksGetResponseDataType.raml
  sportGetResponseDataType: !include dataTypes/sportsGetResponseDataType.raml
  sportsListGetResponseDataType: !include dataTypes/sportsGetResponseDataType.raml