#%RAML 1.0 Library
usage: Collection to Centralize Data Types for MC University Records APIs

types:
  studentGetResponseDataType: !include dataTypes/studentGetResponseDataType.raml
  studentListGetResponseDataType: !include dataTypes/studentGetResponseDataType.raml
  studentCreateResponseDataType: !include dataTypes/studentCreateResponseDataType.raml
  studentUpdateResponseDataType: !include dataTypes/studentUpdateResponseDataType.raml
  studentDeleteResponseDataType: !include dataTypes/studentUpdateResponseDataType.raml
  bookGetResponseDataType: !include dataTypes/bookGetResponseDataType.raml
  bookListGetResponseDataType: !include dataTypes/bookGetResponseDataType.raml
  bookCreateResponseDataType: !include dataTypes/bookCreateResponseDataType.raml
  bookUpdateResponseDataType: !include dataTypes/studentsGetResponseDataType.raml
  bookDeleteResponseDataType: !include dataTypes/studentsGetResponseDataType.raml
  sportGetResponseDataType: !include dataTypes/studentsGetResponseDataType.raml
  sportListGetResponseDataType: !include dataTypes/studentsGetResponseDataType.raml
  sportCreateResponseDataType: !include dataTypes/studentsGetResponseDataType.raml
  sportUpdateResponseDataType: !include dataTypes/studentsGetResponseDataType.raml
  sportDeleteResponseDataType: !include dataTypes/studentsGetResponseDataType.raml