#%RAML 1.0 DataType
usage: Book Properties
type: object

properties:
  bookId:
    description: Book's asset ID
    type: string
    minLength: 6
  title:
    description: Book's title
    type: string
  author:
    description: Author's name
    type: string
  publisher:
    description: Publisher's name
    type: string