#%RAML 1.0 DataType
usage: Sport Properties
type: object

properties:
  sportCode:
    description: Sport code
    type: string
    minLength: 6
  title:
    description: Sport's name
    type: string
  instructor:
    description: Instructor's name
    type: string
  publisher:
    description: Publisher's name
    type: string