#%RAML 1.0 DataType
usage: Books List Properties
type: array

items:
  type: object
  properties:
    sportCode:
      description: Sport code
      type: string
      minLength: 6
    title:
      description: Sport's name
      type: string
    instructor:
      description: Instructor's name
      type: string
    schedule:
      description: Sport's schedule
      type: array
      items:
        type: object
        properties:
          day:
            description: Day when sport is taught
            type: enum
          time:
            description: Time when sport is taught
            type: array
            items:
              type: string