#%RAML 1.0 DataType
usage: Student Properties
type: object

properties:
  lastName:
    description: Last name of the student
    type: string
  firstName:
    description: First name of the student
    type: string
  subjects:
    description: Course Title
    type: array
    items:
      type: string